"""Synthetic sample Live Set Sounds for tests.

Generated by varying the (generated) Init Sound across valid field ranges, so
the test suite ships no captured device data. Deterministic: ``make_sound``
returns the same sound for the same (page, set).
"""
from __future__ import annotations

from cp_liveset import JSON_FORMAT, LiveSetSound, init_sound


def make_sound(page: int, set_no: int) -> LiveSetSound:
    """A deterministic, valid, distinct LiveSetSound for (page, set)."""
    ls = init_sound()
    seed = page * 8 + set_no
    # space-padded to the full 15-char name field (exercises trailing-space
    # handling), e.g. "Test 1-1       ".
    ls.common.name = f"Test {page}-{set_no}".ljust(15)
    ls.common.reverb_switch = seed % 2
    ls.common.reverb_time = seed % 128
    ls.common.delay_switch = (seed + 1) % 2
    ls.common.delay_time = (seed * 3) % 100

    piano = ls.sections.piano
    piano.common.section_switch = 1
    piano.common.section_volume = (seed * 2) % 128
    piano.common.tone = (seed * 5) % 128
    piano.common.reverb_depth = seed % 128
    piano.common.delay_depth = (seed * 2) % 128
    piano.specific.piano_effect_switch = seed % 2
    piano.specific.piano_effect_depth = (seed * 3) % 128

    epiano = ls.sections.epiano
    epiano.common.section_switch = seed % 2
    epiano.common.section_volume = (seed * 4) % 128

    ls.zones[0].zone_switch = 1
    ls.zones[0].transmit_channel = seed % 16
    ls.zones[0].note_limit_high = 100
    return ls


def make_sample_doc(pages: int = 5) -> dict:
    """A cp88-cp73-liveset-v1 document of sample sounds (pages 1..`pages`,
    sets 1-8)."""
    out: dict = {"format": JSON_FORMAT, "pages": {}}
    for p in range(1, pages + 1):
        out["pages"][str(p)] = {
            str(s): make_sound(p, s).model_dump(mode="json") for s in range(1, 9)
        }
    return out
